<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlaisePascal.GestoreUdienze.Domain\BlaisePascal.GestoreUdienze.Domain.csproj" />
    <ProjectReference Include="..\BlaisePascal.GestoreUdienze.Application\BlaisePascal.GestoreUdienze.Application.csproj" />
    <ProjectReference Include="..\BlaisePascal.GestoreUdienze.Infrastructure\BlaisePascal.GestoreUdienze.Infrastructure.csproj" />
  </ItemGroup>

</Project>
